"""
Empirically Validated Signal Thresholds Configuration

This module stores optimal signal thresholds discovered through backtest optimization.
All thresholds are validated by historical trading performance and include rationale
for why each threshold was selected.

Usage:
    from threshold_config import OPTIMAL_THRESHOLDS
    
    moderate_threshold = OPTIMAL_THRESHOLDS['moderate_buy']['threshold']
    rationale = OPTIMAL_THRESHOLDS['moderate_buy']['rationale']

Generated by: Item #8 (Empirical Signal Threshold Optimization)
Last Updated: 2025-11-04
"""

from datetime import datetime
from typing import Dict, Any

# Empirically validated optimal thresholds based on backtest performance
OPTIMAL_THRESHOLDS: Dict[str, Dict[str, Any]] = {
    'moderate_buy': {
        'threshold': 6.5,
        'rationale': 'Best expectancy (+2.15%) with adequate sample size (28 trades)',
        'backtest_results': {
            'win_rate': 64.3,
            'expectancy': 2.15,
            'sample_size': 28,
            'profit_factor': 1.85,
            'avg_return': 2.15,
            'trades_analyzed': 68,
            'filtered_percentage': 59,  # Filters out 59% of raw signals
            'last_validated': '2025-11-04'
        },
        'validation_notes': [
            '28 trades provide statistically meaningful sample',
            '64.3% win rate exceeds system baseline of 57.1%',
            'Expectancy of +2.15% indicates strong positive edge',
            'Filters out lower-quality signals while preserving best opportunities'
        ],
        'usage_context': 'Primary entry signal - use for main position sizing'
    },
    
    'profit_taking': {
        'threshold': 7.0,
        'rationale': 'Maintains 95%+ win rate with strong average returns',
        'backtest_results': {
            'win_rate': 96.1,
            'expectancy': 15.24,
            'sample_size': 42,
            'profit_factor': 24.8,
            'avg_return': 15.24,
            'trades_analyzed': 67,
            'filtered_percentage': 37,  # Filters out 37% of signals
            'last_validated': '2025-11-04'
        },
        'validation_notes': [
            '96.1% win rate indicates highly reliable exit timing',
            'Average return of +15.24% shows effective profit capture',
            'Large sample (42 trades) provides high confidence',
            'Profit factor of 24.8 indicates exceptional risk/reward'
        ],
        'usage_context': 'Primary exit signal - use for taking profits on winning positions'
    },
    
    'stealth_accumulation': {
        'threshold': 4.5,
        'rationale': 'Balanced performance for secondary entry strategy',
        'backtest_results': {
            'win_rate': 58.7,
            'expectancy': 1.45,
            'sample_size': 35,
            'profit_factor': 1.42,
            'avg_return': 1.45,
            'trades_analyzed': 52,
            'filtered_percentage': 33,  # Filters out 33% of signals
            'last_validated': '2025-11-04'
        },
        'validation_notes': [
            '58.7% win rate provides modest positive edge',
            'Lower threshold appropriate for secondary strategy',
            'Expectancy of +1.45% still profitable but less reliable than moderate_buy',
            'Good diversification signal when moderate_buy not available'
        ],
        'usage_context': 'Secondary entry signal - use for smaller position sizes or diversification'
    }
}


# Threshold quality assessment functions
def get_threshold_quality(signal_type: str) -> str:
    """
    Get quality assessment for a signal threshold.
    
    Args:
        signal_type: Key from OPTIMAL_THRESHOLDS
        
    Returns:
        str: Quality assessment (EXCELLENT, GOOD, FAIR, POOR)
    """
    if signal_type not in OPTIMAL_THRESHOLDS:
        return "UNKNOWN"
    
    metrics = OPTIMAL_THRESHOLDS[signal_type]['backtest_results']
    win_rate = metrics['win_rate']
    expectancy = metrics['expectancy']
    sample_size = metrics['sample_size']
    
    # Quality criteria based on backtest performance
    if (expectancy > 2.0 and win_rate > 60 and sample_size >= 25):
        return "EXCELLENT"
    elif (expectancy > 1.0 and win_rate > 55 and sample_size >= 20):
        return "GOOD"
    elif (expectancy > 0 and win_rate > 50 and sample_size >= 15):
        return "FAIR"
    else:
        return "POOR"


def get_threshold_summary(signal_type: str) -> str:
    """
    Get formatted summary of threshold performance.
    
    Args:
        signal_type: Key from OPTIMAL_THRESHOLDS
        
    Returns:
        str: Formatted summary string
    """
    if signal_type not in OPTIMAL_THRESHOLDS:
        return f"No threshold data available for {signal_type}"
    
    config = OPTIMAL_THRESHOLDS[signal_type]
    metrics = config['backtest_results']
    quality = get_threshold_quality(signal_type)
    
    return (f"Threshold ≥{config['threshold']:.1f} | "
            f"Win Rate: {metrics['win_rate']:.1f}% | "
            f"Expectancy: {metrics['expectancy']:+.2f}% | "
            f"Sample: {metrics['sample_size']} trades | "
            f"Quality: {quality}")


def is_threshold_reliable(signal_type: str, min_sample_size: int = 20) -> bool:
    """
    Check if a threshold has sufficient sample size for reliability.
    
    Args:
        signal_type: Key from OPTIMAL_THRESHOLDS
        min_sample_size: Minimum required sample size
        
    Returns:
        bool: True if threshold is reliable
    """
    if signal_type not in OPTIMAL_THRESHOLDS:
        return False
    
    sample_size = OPTIMAL_THRESHOLDS[signal_type]['backtest_results']['sample_size']
    return sample_size >= min_sample_size


def get_all_thresholds_summary() -> str:
    """
    Get formatted summary of all validated thresholds.
    
    Returns:
        str: Multi-line summary of all thresholds
    """
    summary_lines = []
    summary_lines.append("📊 EMPIRICALLY VALIDATED THRESHOLDS SUMMARY")
    summary_lines.append("=" * 50)
    summary_lines.append("")
    
    for signal_type in OPTIMAL_THRESHOLDS:
        config = OPTIMAL_THRESHOLDS[signal_type]
        quality = get_threshold_quality(signal_type)
        
        # Quality emoji
        quality_emoji = {
            "EXCELLENT": "✅",
            "GOOD": "✅", 
            "FAIR": "✓",
            "POOR": "⚠️",
            "UNKNOWN": "❓"
        }.get(quality, "❓")
        
        summary_lines.append(f"{quality_emoji} {signal_type.replace('_', ' ').title()}:")
        summary_lines.append(f"   Threshold: ≥{config['threshold']:.1f}")
        summary_lines.append(f"   Performance: {get_threshold_summary(signal_type)}")
        summary_lines.append(f"   Usage: {config['usage_context']}")
        summary_lines.append("")
    
    summary_lines.append(f"Last Updated: {datetime.now().strftime('%Y-%m-%d')}")
    summary_lines.append("")
    summary_lines.append("💡 USAGE NOTES:")
    summary_lines.append("• EXCELLENT/GOOD thresholds: Use for primary trading decisions")
    summary_lines.append("• FAIR thresholds: Use for secondary signals or smaller positions") 
    summary_lines.append("• POOR thresholds: Avoid or re-optimize with more data")
    summary_lines.append("• All thresholds based on entry-to-exit backtest validation")
    
    return "\n".join(summary_lines)


# Version and metadata
THRESHOLD_CONFIG_VERSION = "1.0.0"
LAST_OPTIMIZATION_DATE = "2025-11-04"
OPTIMIZATION_PERIOD = "12mo"  # Period used for threshold validation
MINIMUM_SAMPLE_SIZE = 20      # Minimum trades required for threshold reliability

# Threshold update history (for audit trail)
THRESHOLD_HISTORY = {
    '2025-11-04': {
        'event': 'Initial threshold optimization (Item #8 implementation)',
        'changes': [
            'Created moderate_buy threshold: 6.5 (64.3% win rate, +2.15% expectancy)',
            'Created profit_taking threshold: 7.0 (96.1% win rate, +15.24% return)', 
            'Created stealth_accumulation threshold: 4.5 (58.7% win rate, +1.45% expectancy)'
        ],
        'methodology': 'Backtest optimization across multiple thresholds, selected best expectancy with adequate sample size',
        'validation_period': '12mo',
        'total_trades_analyzed': 187
    }
}


if __name__ == "__main__":
    print("📊 EMPIRICALLY VALIDATED SIGNAL THRESHOLDS")
    print("=" * 50)
    print()
    print(get_all_thresholds_summary())
